 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     machine: true
     executor: win/default 
    
     steps:
       - checkout
       - run: |
       docker info
       docker build -t foodly -f Dockerfile

       - run: |
       docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
       docker tag foodly registry.heroku.com/$HEROKU_APP_NAME/web
       docker push registry.heroku.com/$HEROKU_APP_NAME/web
       curl https://cli-assets.heroku.com/install.sh | sh
       heroku container:release web -a $HEROKU_APP_NAME